neopetsproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('petfinder.urls')),
    path('admin/', admin.site.urls),
]

petfinder/urls.py
from django.urls import path

from . import views

app_name = 'petfinder'
urlpatterns = [
    path('add/pet/', views.addFavorite, name='add_favorite'),
    path('delete/pet/', views.deleteFavorite, name='delete_favorite'),
    path('favorites/', views.listFavorites, name="favorites"),
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),
]

petfinder/models.py
from django.db import models

class Pet(models.Model):
    animal_id = models.IntegerField(primary_key=True)
    animal_type = models.CharField(max_length=50)
    detail_link = models.CharField(max_length=300)
    image_small = models.CharField(max_length=300, default='http://placekitten.com/100/150')
    image_full = models.CharField(max_length=300, default='http://placekitten.com/400/550')
    age = models.CharField(max_length=50)
    gender = models.CharField(max_length=50)
    size = models.CharField(max_length=50, null=True)
    description = models.CharField(max_length=500, null=True)
    status = models.CharField(max_length=50, null=True)
    name = models.CharField(max_length=50)
    zipcode = models.IntegerField()

petfinder/views.py
import os
import datetime
import requests
import json

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from .models import Pet

def index(request):
    updatePetfinderToken()
    context = {
        'pet_types': getAnimalTypes(),
        'genders': ['male', 'female'],
        'statuses': ['adoptable', 'adopted', 'found']
    }
    return render(request, 'petfinder/index.html', context)

def search(request):
    updatePetfinderToken()
    url = os.getenv('PETFINDER_BASE_URL') + '/v2/animals'
    request_headers = {
        'Authorization': 'Bearer ' + os.getenv('PETFINDER_ACCESS_TOKEN')
    }
    url_params = {}
    for field in request.GET:
        if request.GET.getlist(field) and request.GET.getlist(field)[0]:
            url_params[field] = ','.join(request.GET.getlist(field))
    response = requests.get(url, params=url_params, headers=request_headers)
    response = json.loads(response.text)
    favorites = Pet.objects.all()
    favorites = [f.animal_id for f in favorites]

    context = {
        'pet_types': getAnimalTypes(),
        'genders': ['male', 'female'],
        'statuses': ['adoptable', 'adopted', 'found'],
        'results': response,
        'favorites': favorites
    }
    return render(request, 'petfinder/search.html', context)

def addFavorite(request):
    if request.POST and request.is_ajax():
        updatePetfinderToken()
        response = requests.get(
            os.getenv('PETFINDER_BASE_URL')+'/v2/animals/'+request.POST['id'],
            headers={'Authorization': 'Bearer ' + os.getenv('PETFINDER_ACCESS_TOKEN')}
        )
        response = json.loads(response.text)
        if len(response['animal']['photos']):
            small_image = response['animal']['photos'][0]['small']
            full_image = response['animal']['photos'][0]['full']
        else:
            if response['animal']['type'] == 'Cat':
                small_image = 'https://placekitten.com/100/150'
                full_image = 'https://placekitten.com/400/550'
            elif response['animal']['type'] == 'Dog':
                small_image = 'https://placedog.net/100/150'
                full_image = 'https://placedog.net/400/550'
            else:
                small_image = 'https://via.placeholder.com/100x150'
                full_image = 'https://via.placeholder.com/400x550'

        if not Pet.objects.filter(animal_id=response['animal']['id']).exists():
            favorite = Pet(
                animal_id=response['animal']['id'],
                animal_type=response['animal']['type'],
                detail_link=response['animal']['url'],
                image_small=small_image,
                image_full=full_image,
                age=response['animal']['age'],
                gender=response['animal']['gender'],
                size=response['animal']['size'],
                name=response['animal']['name'],
                description=response['animal']['description'],
                status=response['animal']['status'],
                zipcode=response['animal']['contact']['address']['postcode']
            )
            favorite.save()

            return JsonResponse({'message': 'Pet added to favorites'})

        return JsonResponse({'message': 'Pet already exists in favorites'})

def deleteFavorite(request):
    if request.POST and request.is_ajax():
        try:
            favorite = Pet.objects.get(animal_id=request.POST['id'])
            favorite.delete()
        except Exception:
            return JsonResponse({'message': 'Pet is not favorited, no action required'})

    return JsonResponse({'message': 'Pet removed from favorites'})

def listFavorites(request):
    favorites = Pet.objects.all()
    context = {
        'favorites': favorites,
        'google_api_key': os.getenv('GOOGLE_MAPS_API_KEY')
    }

    return render(request, 'petfinder/favorites.html', context)


# helpers
def updatePetfinderToken():
    url = os.getenv('PETFINDER_BASE_URL') + '/v2/oauth2/token'
    url_params = {
        'grant_type': 'client_credentials',
        'client_id': os.getenv('PETFINDER_API_KEY'),
        'client_secret': os.getenv('PETFINDER_API_SECRET')
    }
    response = requests.post(url, data=url_params)
    serializedText = json.loads(response.text)

    os.environ['PETFINDER_ACCESS_TOKEN'] = serializedText['access_token']

def getAnimalTypes():
    updatePetfinderToken()
    types_url = os.getenv('PETFINDER_BASE_URL') + '/v2/types'
    request_headers = {
        'Authorization': 'Bearer ' + os.getenv('PETFINDER_ACCESS_TOKEN')
    }
    response = requests.get(types_url, headers=request_headers)
    response = json.loads(response.text)

    return [t['name'] for t in response['types']]

petfinder/templates/petfinder/favorites.html
{% extends 'base.html' %}

{% csrf_token %}
{% block javascript %}
<script>
    var map;
    var markers = {};

    function favorite(element) {
        var csrftoken = getCookie('csrftoken');
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        $.ajax({
            type: 'POST',
            url: '/' + element.name + '/pet/',
            dataType: 'json',
            data: {
                id: element.id
            },
            success: function(response) {
                markers[element.id].setMap(null);
            }
        });
        $('#row-'+element.id).remove()
    }

    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: 38.3079827, lng: -97.8934871},
            zoom: 4
        });

        var geocoder = new google.maps.Geocoder();
        {% for entry in favorites %}
            geocoder.geocode({
                    address: '{{ entry.zipcode }}',
                    region: 'US'
                },
                function(result, status) {
                    if (status == 'OK' && result.length > 0) {
                        var icon = {
                            url: '{{ entry.image_small }}',
                            scaledSize: new google.maps.Size(30,35),
                            origin: new google.maps.Point(0,0),
                            anchor: new google.maps.Point(0,0)
                        };
                        markers['{{ entry.animal_id }}'] = new google.maps.Marker({
                            position: result[0].geometry.location,
                            animation: google.maps.Animation.DROP,
                            map: map,
                            icon: icon,
                            title: '{{ entry.name }}',
                            url: '{{ entry.detail_link }}'
                        });
                        google.maps.event.addListener(markers['{{ entry.animal_id }}'], 'click', function() {
                            window.open(this.url, '_blank');
                        });
                    }
                }
            );
        {% endfor %}
    }

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
</script>
{% endblock javascript %}

{% block content %}
<div class="map-container" id="map"></div>
<div class="container container-fluid">
    <div class="row">
        {% for entry in favorites %}
            <div class="col-12 col-md-6 col-lg-3 d-flex align-items-stretch p-2" id="row-{{ entry.animal_id }}">
                <div class="card full-width">
                    <div class="card-image">
                        <a href="{{ entry.detail_link }}" target="_blank">
                            <img class="card-img-top pet-image" src="{{ entry.image_full }}" onerror="this.src='https://placekitten.com/400/550'">
                        </a>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ entry.name }}</h5>
                        <p class="card-text">{{ entry.description }}</p>
                    </div>
                    <ul class="list-group list-group-flush text-center">
                        <li class="list-group-item">{{ entry.animal_type}} ᛫ {{ entry.status }}</li>
                        <li class="list-group-item">{{ entry.age}} ᛫ {{ entry.gender }} ᛫ {{ entry.size }}</li>
                    </ul>
                    <div class="card-body text-center favorite-button">
                        <button class="btn btn-danger no-border-radius" onclick="favorite(this)" name="delete" id="{{ entry.animal_id }}">
                            Remove Favorite
                        </button>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

petfinder/templates/petfinder/index.html
{% extends 'base.html' %}

{% load customTags %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-3 site-header">Welcome to Neo-pets</h1>
        <p class="lead">Find your next best friend</p>
        <form action="{% url 'petfinder:search' %}">
            <div class="form-row">
                <div class="form-group col-12 col-lg-9">
                    <input
                        type="text"
                        name="name"
                        class="form-control form-control-lg no-border-radius"
                        placeholder="Animal name"
                        value="{{ request.GET.name }}">
                </div>
            </div>
            <div class="form-row">
                <div class="col-6 col-lg-3">
                    {% for gender in genders %}
                        <div class="custom-control custom-checkbox">
                            <input
                                class="custom-control-input"
                                name="gender"
                                value="{{ gender }}"
                                type="checkbox"
                                id="{{ gender }}"
                                {% if gender in request.GET|get_list:'gender' %}checked{% endif %}>
                            <label class="custom-control-label" for="{{ gender }}">
                                {{ gender }}
                            </label>
                        </div>
                    {% endfor %}
                </div>
                <div class="col-6 col-lg-3">
                    {% for status in statuses %}
                        <div class="custom-control custom-radio">
                            <input
                                class="custom-control-input"
                                name="status"
                                value="{{ status }}"
                                type="radio"
                                id="{{ status }}"
                                {% if status == request.GET.status %}checked{% endif %}>
                            <label class="custom-control-label" for="{{ status }}">
                                {{ status }}
                            </label>
                        </div>
                    {% endfor %}
                </div>
                <div class="col-12 col-lg-3">
                    <div class="form-group">
                        <select name="type" class="form-control form-control-lg no-border-radius" id="type">
                            {% for pet in pet_types %}
                                <option
                                    value="{{ pet }}"
                                    {% if pet == request.GET.type %}selected{% endif %}>
                                    {{ pet }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <input type="submit" class="btn btn-primary mb2 no-border-radius" value="Search">
        </form>
    </div>
</div>
{% endblock content %}

petfinder/templates/petfinder/search.html
{% csrf_token %}
{% block javascript %}
<script>
    function favorite(element) {
        var csrftoken = getCookie('csrftoken');
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        $.ajax({
            type: 'POST',
            url: '/' + element.name + '/pet/',
            dataType: 'json',
            data: {
                id: element.id
            },
            success: function(response, status) {
                if (element.name == "add") {
                    element.className = "btn btn-danger no-border-radius";
                    element.name = "delete";
                    element.innerHTML = "Remove favorite";
                } else {
                    element.className = "btn btn-success no-border-radius";
                    element.name = "add";
                    element.innerHTML = "Add to favorites";
                }
            }
        });
        element.className = "btn btn-info no-border-radius";
        element.innerHTML = element.name == "add" ? "Adding pet..." : "Removing pet...";
    }

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
</script>
{% endblock javascript %}

{% block content %}
{% include 'petfinder/index.html' %}
<div class="container container-fluid">
    <div class="row">
        {% for entry in results.animals %}
            <div class="col-12 col-md-6 col-lg-3 d-flex align-items-stretch p-2">
                <div class="card full-width">
                    <div class="card-image">
                        <a href="{{ entry.url }}" target="_blank">
                            <img class="card-img-top pet-image" src="{{ entry.photos.0.full }}" onerror="this.src='https://via.placeholder.com/400x550'">
                        </a>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ entry.name }}</h5>
                        <p class="card-text">{{ entry.description }}</p>
                    </div>
                    <ul class="list-group list-group-flush text-center">
                        <li class="list-group-item">{{ entry.type}} ᛫ {{ entry.status }}</li>
                        <li class="list-group-item">{{ entry.age}} ᛫ {{ entry.gender }} ᛫ {{ entry.size }}</li>
                    </ul>
                    <div class="card-body text-center favorite-button">
                        {% if entry.id in favorites %}
                            <button class="btn btn-danger no-border-radius" onclick="favorite(this)" name="delete" id="{{ entry.id }}">
                                Remove Favorite
                            </button>
                        {% else %}
                            <button class="btn btn-success no-border-radius" onclick="favorite(this)" name="add" id="{{ entry.id }}">
                                Add to Favorites
                            </button>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% load static %}

        <title>Neo-Pets</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'petfinder/style.css' %}">
    </head>
    <body>
        {% include 'nav.html' %}

        {% block content %}{% endblock content %}

        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key={{ google_api_key }}&callback=initMap" async defer></script>
        {% block javascript %}{% endblock javascript %}
    </body>
</html>

templates/nav.html
<div class="text-right padding-md">
    <div class="float-left">
        <a href="{% url 'petfinder:index' %}" class="btn btn-link">
            Home
        </a>
    </div>
    <div>
        <a href="{% url 'petfinder:favorites' %}" class="btn btn-link">
            Favorites
        </a>
    </div>
</div>